### ISSUE TITLE
UI Design of Blog

### ISSUE THREAD

**Issue by bobateadev** [PaddlePaddle/PaddlePaddle.org#61] opened 2017-09-22 22:07 UTC

**Comment by varunarora** [comment] 2017-10-11 05:33
Keeping old design. @cs2be Could we close this?

**Comment by varunarora** [comment] 2017-10-13 18:38
Actually, we are breaking the original design. It used to be:

<img width="1452" alt="paddleblog-original" src="https://user-images.githubusercontent.com/629203/31560866-d78a8c36-b00a-11e7-835e-9977147e0d0b.png">

But we are proposing to render this guy:
<img width="1450" alt="paddleblog-new" src="https://user-images.githubusercontent.com/629203/31560865-d763314a-b00a-11e7-80fb-0fb2ed9ce11c.png">

Which is not consistent with what was intended.

**Comment by daming-lu** [comment] 2017-10-18 00:08
http://staging.paddlepaddle.org:82/blog/2017/07/25/pytorch-vs-tensorflow.html

http://staging.paddlepaddle.org:82/blog/

**Closed by daming-lu** 2017-10-18 00:08 UTC
Labels: bug, needs clarification
